import React, { useState } from 'react';
import { FileCode, Download, Copy, Check, Plus, Trash2, Globe, Shield, RefreshCw, Layers } from 'lucide-react';
import { triggerConfetti } from '../../utils/confetti';

interface TechnicalGeneratorProps {
  mode: 'robotstxt' | 'sitemap' | 'hreflang' | 'redirects' | 'disavow';
}

export function TechnicalGenerator({ mode }: TechnicalGeneratorProps) {
  const [copied, setCopied] = useState(false);

  // 1. Robots.txt State
  const [userAgent, setUserAgent] = useState('*');
  const [crawlDelay, setCrawlDelay] = useState('0');
  const [disallowPaths, setDisallowPaths] = useState('/admin/\n/api/private/\n/checkout/\n/*.json$');
  const [allowPaths, setAllowPaths] = useState('/public/\n/assets/\n/category/');
  const [sitemapUrl, setSitemapUrl] = useState('https://quickcalculator.app/sitemap.xml');
  const [blockAiBots, setBlockAiBots] = useState(true);

  // 2. XML Sitemap State
  const [sitemapUrls, setSitemapUrls] = useState(
    'https://quickcalculator.app/\nhttps://quickcalculator.app/category/finance-calculators\nhttps://quickcalculator.app/category/seo-website-tools\nhttps://quickcalculator.app/category/developer-tools\nhttps://quickcalculator.app/category/pdf-tools\nhttps://quickcalculator.app/tool/sip-calculator\nhttps://quickcalculator.app/tool/emi-loan-calculator'
  );
  const [changeFreq, setChangeFreq] = useState('daily');
  const [priority, setPriority] = useState('0.8');

  // 3. Canonical & Hreflang State
  const [canonicalUrl, setCanonicalUrl] = useState('https://quickcalculator.app/tool/serp-snippet-google-preview-simulator');
  const [hreflangList, setHreflangList] = useState([
    { lang: 'en-US', url: 'https://quickcalculator.app/tool/serp-snippet-google-preview-simulator' },
    { lang: 'en-GB', url: 'https://quickcalculator.app/uk/tool/serp-snippet-google-preview-simulator' },
    { lang: 'es-ES', url: 'https://quickcalculator.app/es/tool/serp-snippet-google-preview-simulator' },
    { lang: 'de-DE', url: 'https://quickcalculator.app/de/tool/serp-snippet-google-preview-simulator' },
    { lang: 'x-default', url: 'https://quickcalculator.app/tool/serp-snippet-google-preview-simulator' }
  ]);

  // 4. Redirect Rule State
  const [serverType, setServerType] = useState<'htaccess' | 'nginx'>('htaccess');
  const [redirectType, setRedirectType] = useState<'301' | '302'>('301');
  const [oldPath, setOldPath] = useState('/old-calculator-path');
  const [newUrl, setNewUrl] = useState('https://quickcalculator.app/new-calculator-path');
  const [redirectPattern, setRedirectPattern] = useState<'exact' | 'http_to_https' | 'non_www_to_www' | 'trailing_slash'>('exact');

  // 5. Disavow State
  const [disavowEntries, setDisavowEntries] = useState(
    `# Disavow spam link farm network - March 2026
domain:toxicbacklinksite.com
domain:spamseoforumdirectory.net
# Specific toxic scraper URL
https://badscraper.biz/spam-article-page.html`
  );

  const handleCopy = (text: string) => {
    navigator.clipboard.writeText(text);
    setCopied(true);
    triggerConfetti(0.3);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownloadFile = (filename: string, content: string, mime: string = 'text/plain') => {
    const blob = new Blob([content], { type: `${mime};charset=utf-8;` });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = filename;
    link.click();
    URL.revokeObjectURL(url);
    triggerConfetti(0.4);
  };

  // Generate Robots.txt
  const generateRobotsTxt = () => {
    let out = `# Robots.txt Directive generated by Quick Calculator\n`;
    out += `User-agent: ${userAgent}\n`;
    if (parseInt(crawlDelay) > 0) {
      out += `Crawl-delay: ${crawlDelay}\n`;
    }
    allowPaths.split('\n').filter(Boolean).forEach(p => {
      out += `Allow: ${p.trim()}\n`;
    });
    disallowPaths.split('\n').filter(Boolean).forEach(p => {
      out += `Disallow: ${p.trim()}\n`;
    });

    if (blockAiBots) {
      out += `\n# AI Scraping Crawlers\n`;
      out += `User-agent: GPTBot\nDisallow: /\n\nUser-agent: CCBot\nDisallow: /\n\nUser-agent: ClaudeBot\nDisallow: /\n`;
    }

    if (sitemapUrl.trim()) {
      out += `\nSitemap: ${sitemapUrl.trim()}\n`;
    }
    return out;
  };

  // Generate XML Sitemap
  const generateSitemapXml = () => {
    const today = new Date().toISOString().split('T')[0];
    const urls = sitemapUrls.split('\n').map(u => u.trim()).filter(Boolean);
    let xml = `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n`;
    urls.forEach((u, i) => {
      const p = i === 0 ? '1.0' : priority;
      xml += `  <url>\n    <loc>${u}</loc>\n    <lastmod>${today}</lastmod>\n    <changefreq>${changeFreq}</changefreq>\n    <priority>${p}</priority>\n  </url>\n`;
    });
    xml += `</urlset>`;
    return xml;
  };

  // Generate Hreflang Tags
  const generateHreflangCode = () => {
    let out = `<!-- Canonical & International Multi-Language Tags -->\n<link rel="canonical" href="${canonicalUrl}" />\n`;
    hreflangList.forEach(item => {
      out += `<link rel="alternate" hreflang="${item.lang}" href="${item.url}" />\n`;
    });
    return out;
  };

  // Generate Redirect Rules
  const generateRedirectRule = () => {
    const is301 = redirectType === '301';
    const statusFlag = is301 ? 'R=301,L' : 'R=302,L';
    const nginxStatus = is301 ? 'permanent' : 'redirect';

    if (redirectPattern === 'http_to_https') {
      if (serverType === 'htaccess') {
        return `RewriteEngine On\nRewriteCond %{HTTPS} off\nRewriteRule ^(.*)$ https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]`;
      }
      return `server {\n  listen 80;\n  server_name yourdomain.com www.yourdomain.com;\n  return 301 https://$host$request_uri;\n}`;
    }

    if (redirectPattern === 'non_www_to_www') {
      if (serverType === 'htaccess') {
        return `RewriteEngine On\nRewriteCond %{HTTP_HOST} !^www\\. [NC]\nRewriteRule ^(.*)$ https://www.%{HTTP_HOST}/$1 [R=301,L]`;
      }
      return `server {\n  server_name yourdomain.com;\n  return 301 https://www.yourdomain.com$request_uri;\n}`;
    }

    if (redirectPattern === 'trailing_slash') {
      if (serverType === 'htaccess') {
        return `RewriteEngine On\nRewriteCond %{REQUEST_FILENAME} !-d\nRewriteRule ^(.*)/$ /$1 [L,R=301]`;
      }
      return `rewrite ^/(.*)/$ /$1 permanent;`;
    }

    // Exact Path Redirect
    if (serverType === 'htaccess') {
      return `RewriteEngine On\nRedirect ${redirectType} ${oldPath} ${newUrl}`;
    }
    return `location = ${oldPath} {\n  return ${redirectType} ${newUrl};\n}`;
  };

  return (
    <div className="space-y-6">
      {/* 1. Robots.txt Generator View */}
      {mode === 'robotstxt' && (
        <div className="space-y-5">
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <div className="p-4 rounded-2xl bg-slate-950/90 border border-cyan-500/20 space-y-3">
              <div>
                <label className="text-xs font-mono font-bold text-cyan-300">User-Agent</label>
                <select
                  value={userAgent}
                  onChange={(e) => setUserAgent(e.target.value)}
                  className="w-full mt-1 p-2 rounded-xl bg-slate-900 border border-slate-700 text-xs font-mono text-cyan-100"
                >
                  <option value="*">* (All Search Engine Robots)</option>
                  <option value="Googlebot">Googlebot (Google Search)</option>
                  <option value="Bingbot">Bingbot (Microsoft Bing)</option>
                  <option value="Baiduspider">Baiduspider (Baidu Search)</option>
                  <option value="YandexBot">YandexBot (Yandex)</option>
                </select>
              </div>

              <div>
                <label className="text-xs font-mono font-bold text-cyan-300">Disallowed Directories (1 per line)</label>
                <textarea
                  rows={3}
                  value={disallowPaths}
                  onChange={(e) => setDisallowPaths(e.target.value)}
                  className="w-full mt-1 p-2 rounded-xl bg-slate-900 border border-slate-700 text-xs font-mono text-rose-300"
                />
              </div>

              <div>
                <label className="text-xs font-mono font-bold text-cyan-300">Allowed Paths (1 per line)</label>
                <textarea
                  rows={2}
                  value={allowPaths}
                  onChange={(e) => setAllowPaths(e.target.value)}
                  className="w-full mt-1 p-2 rounded-xl bg-slate-900 border border-slate-700 text-xs font-mono text-emerald-300"
                />
              </div>

              <div className="flex items-center gap-2 pt-2">
                <input
                  type="checkbox"
                  id="blockAi"
                  checked={blockAiBots}
                  onChange={(e) => setBlockAiBots(e.target.checked)}
                  className="rounded text-cyan-500 bg-slate-900 border-slate-700 cursor-pointer"
                />
                <label htmlFor="blockAi" className="text-xs font-mono text-slate-300 cursor-pointer">
                  Disallow AI Scraping Bots (GPTBot, CCBot, ClaudeBot)
                </label>
              </div>
            </div>

            {/* Live Generated Output */}
            <div className="p-4 rounded-2xl bg-slate-950 border border-cyan-500/30 space-y-3">
              <div className="flex items-center justify-between">
                <span className="text-xs font-mono font-bold text-cyan-300">Generated robots.txt</span>
                <div className="flex gap-2">
                  <button
                    type="button"
                    onClick={() => handleCopy(generateRobotsTxt())}
                    className="px-2.5 py-1 rounded bg-slate-800 text-xs font-mono text-cyan-300 flex items-center gap-1 cursor-pointer"
                  >
                    <Copy className="w-3 h-3" />
                    <span>{copied ? 'Copied!' : 'Copy'}</span>
                  </button>
                  <button
                    type="button"
                    onClick={() => handleDownloadFile('robots.txt', generateRobotsTxt())}
                    className="px-2.5 py-1 rounded bg-cyan-500 text-slate-950 text-xs font-mono font-bold flex items-center gap-1 cursor-pointer"
                  >
                    <Download className="w-3 h-3" />
                    <span>Download .txt</span>
                  </button>
                </div>
              </div>
              <textarea
                rows={10}
                readOnly
                value={generateRobotsTxt()}
                className="w-full p-3 rounded-xl bg-slate-900 border border-slate-800 text-xs font-mono text-cyan-200 focus:outline-none"
              />
            </div>
          </div>
        </div>
      )}

      {/* 2. XML Sitemap Generator View */}
      {mode === 'sitemap' && (
        <div className="space-y-5">
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <div className="p-4 rounded-2xl bg-slate-950/90 border border-cyan-500/20 space-y-3">
              <label className="text-xs font-mono font-bold text-cyan-300">Website URLs (1 URL per line)</label>
              <textarea
                rows={6}
                value={sitemapUrls}
                onChange={(e) => setSitemapUrls(e.target.value)}
                className="w-full p-2.5 rounded-xl bg-slate-900 border border-slate-700 text-xs font-mono text-cyan-100 focus:outline-none focus:border-cyan-400"
              />

              <div className="grid grid-cols-2 gap-2">
                <div>
                  <label className="text-xs font-mono text-slate-400">Change Frequency</label>
                  <select
                    value={changeFreq}
                    onChange={(e) => setChangeFreq(e.target.value)}
                    className="w-full mt-1 p-2 rounded-xl bg-slate-900 border border-slate-700 text-xs font-mono text-cyan-200"
                  >
                    <option value="always">always</option>
                    <option value="hourly">hourly</option>
                    <option value="daily">daily</option>
                    <option value="weekly">weekly</option>
                    <option value="monthly">monthly</option>
                  </select>
                </div>
                <div>
                  <label className="text-xs font-mono text-slate-400">Priority Weight</label>
                  <select
                    value={priority}
                    onChange={(e) => setPriority(e.target.value)}
                    className="w-full mt-1 p-2 rounded-xl bg-slate-900 border border-slate-700 text-xs font-mono text-cyan-200"
                  >
                    <option value="1.0">1.0 (Highest)</option>
                    <option value="0.9">0.9</option>
                    <option value="0.8">0.8 (Standard)</option>
                    <option value="0.5">0.5</option>
                    <option value="0.3">0.3</option>
                  </select>
                </div>
              </div>
            </div>

            {/* XML Output */}
            <div className="p-4 rounded-2xl bg-slate-950 border border-cyan-500/30 space-y-3">
              <div className="flex items-center justify-between">
                <span className="text-xs font-mono font-bold text-cyan-300">Generated sitemap.xml</span>
                <div className="flex gap-2">
                  <button
                    type="button"
                    onClick={() => handleCopy(generateSitemapXml())}
                    className="px-2.5 py-1 rounded bg-slate-800 text-xs font-mono text-cyan-300 flex items-center gap-1 cursor-pointer"
                  >
                    <Copy className="w-3 h-3" />
                    <span>Copy XML</span>
                  </button>
                  <button
                    type="button"
                    onClick={() => handleDownloadFile('sitemap.xml', generateSitemapXml(), 'application/xml')}
                    className="px-2.5 py-1 rounded bg-cyan-500 text-slate-950 text-xs font-mono font-bold flex items-center gap-1 cursor-pointer"
                  >
                    <Download className="w-3 h-3" />
                    <span>Download .xml</span>
                  </button>
                </div>
              </div>
              <textarea
                rows={11}
                readOnly
                value={generateSitemapXml()}
                className="w-full p-3 rounded-xl bg-slate-900 border border-slate-800 text-xs font-mono text-teal-300 focus:outline-none"
              />
            </div>
          </div>
        </div>
      )}

      {/* 3. Canonical & Hreflang Tag Generator View */}
      {mode === 'hreflang' && (
        <div className="space-y-5">
          <div className="p-4 rounded-2xl bg-slate-950/90 border border-cyan-500/20 space-y-3">
            <label className="text-xs font-mono font-bold text-cyan-300">Primary Canonical URL</label>
            <input
              type="url"
              value={canonicalUrl}
              onChange={(e) => setCanonicalUrl(e.target.value)}
              className="w-full px-3 py-2 rounded-xl bg-slate-900 border border-slate-700 text-xs font-mono text-cyan-100"
            />

            <span className="block text-xs font-mono font-bold text-cyan-300 pt-2">
              International Multi-Language Variants
            </span>
            <div className="space-y-2 max-h-48 overflow-y-auto">
              {hreflangList.map((item, idx) => (
                <div key={idx} className="flex gap-2 items-center">
                  <input
                    type="text"
                    value={item.lang}
                    onChange={(e) => {
                      const copy = [...hreflangList];
                      copy[idx].lang = e.target.value;
                      setHreflangList(copy);
                    }}
                    placeholder="Language (e.g. en-US, es-ES)"
                    className="w-28 px-2.5 py-1.5 rounded-lg bg-slate-900 border border-slate-700 text-xs font-mono text-cyan-300"
                  />
                  <input
                    type="url"
                    value={item.url}
                    onChange={(e) => {
                      const copy = [...hreflangList];
                      copy[idx].url = e.target.value;
                      setHreflangList(copy);
                    }}
                    placeholder="Regional URL..."
                    className="flex-1 px-2.5 py-1.5 rounded-lg bg-slate-900 border border-slate-700 text-xs font-mono text-slate-200"
                  />
                  <button
                    type="button"
                    onClick={() => setHreflangList(hreflangList.filter((_, i) => i !== idx))}
                    className="p-1.5 rounded text-rose-400 hover:bg-rose-500/10 cursor-pointer"
                  >
                    <Trash2 className="w-3.5 h-3.5" />
                  </button>
                </div>
              ))}
            </div>

            <button
              type="button"
              onClick={() => setHreflangList([...hreflangList, { lang: 'fr-FR', url: 'https://quickcalculator.app/fr/' }])}
              className="px-3 py-1.5 rounded-lg bg-slate-900 hover:bg-slate-800 text-xs font-mono text-cyan-300 border border-slate-700 flex items-center gap-1.5 cursor-pointer"
            >
              <Plus className="w-3.5 h-3.5" />
              <span>Add Language Variant</span>
            </button>
          </div>

          <div className="p-4 rounded-2xl bg-slate-950 border border-cyan-500/30 space-y-3">
            <div className="flex items-center justify-between">
              <span className="text-xs font-mono font-bold text-cyan-300">Generated &lt;head&gt; HTML Link Tags</span>
              <button
                type="button"
                onClick={() => handleCopy(generateHreflangCode())}
                className="px-3 py-1 rounded-xl bg-cyan-500/10 hover:bg-cyan-500/20 text-cyan-300 border border-cyan-500/30 text-xs font-mono font-bold flex items-center gap-1.5 cursor-pointer"
              >
                <Copy className="w-3 h-3" />
                <span>{copied ? 'Copied Tags!' : 'Copy Code'}</span>
              </button>
            </div>
            <textarea
              rows={6}
              readOnly
              value={generateHreflangCode()}
              className="w-full p-3 rounded-xl bg-slate-900 border border-slate-800 text-xs font-mono text-teal-300 focus:outline-none"
            />
          </div>
        </div>
      )}

      {/* 4. Redirect Rule Generator View */}
      {mode === 'redirects' && (
        <div className="space-y-5">
          <div className="p-4 rounded-2xl bg-slate-950/90 border border-cyan-500/20 space-y-3">
            <div className="grid grid-cols-2 gap-2">
              <div>
                <label className="text-xs font-mono text-cyan-300">Web Server Engine</label>
                <select
                  value={serverType}
                  onChange={(e: any) => setServerType(e.target.value)}
                  className="w-full mt-1 p-2 rounded-xl bg-slate-900 border border-slate-700 text-xs font-mono text-cyan-100"
                >
                  <option value="htaccess">Apache (.htaccess)</option>
                  <option value="nginx">Nginx Server Config</option>
                </select>
              </div>

              <div>
                <label className="text-xs font-mono text-cyan-300">Redirect HTTP Status</label>
                <select
                  value={redirectType}
                  onChange={(e: any) => setRedirectType(e.target.value)}
                  className="w-full mt-1 p-2 rounded-xl bg-slate-900 border border-slate-700 text-xs font-mono text-cyan-100"
                >
                  <option value="301">301 (Permanent - Passes Link Equity)</option>
                  <option value="302">302 (Temporary - Maintenance)</option>
                </select>
              </div>
            </div>

            <div>
              <label className="text-xs font-mono text-cyan-300">Redirect Pattern Preset</label>
              <select
                value={redirectPattern}
                onChange={(e: any) => setRedirectPattern(e.target.value)}
                className="w-full mt-1 p-2 rounded-xl bg-slate-900 border border-slate-700 text-xs font-mono text-cyan-100"
              >
                <option value="exact">Exact Path to New URL</option>
                <option value="http_to_https">Force HTTP to HTTPS</option>
                <option value="non_www_to_www">Force non-WWW to WWW</option>
                <option value="trailing_slash">Strip Trailing Slash</option>
              </select>
            </div>

            {redirectPattern === 'exact' && (
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-2 pt-1">
                <div>
                  <label className="text-[11px] font-mono text-slate-400">Old Relative Path</label>
                  <input
                    type="text"
                    value={oldPath}
                    onChange={(e) => setOldPath(e.target.value)}
                    className="w-full mt-0.5 p-2 rounded-lg bg-slate-900 border border-slate-700 text-xs font-mono text-rose-300"
                  />
                </div>
                <div>
                  <label className="text-[11px] font-mono text-slate-400">New Target URL</label>
                  <input
                    type="url"
                    value={newUrl}
                    onChange={(e) => setNewUrl(e.target.value)}
                    className="w-full mt-0.5 p-2 rounded-lg bg-slate-900 border border-slate-700 text-xs font-mono text-emerald-300"
                  />
                </div>
              </div>
            )}
          </div>

          <div className="p-4 rounded-2xl bg-slate-950 border border-cyan-500/30 space-y-3">
            <div className="flex items-center justify-between">
              <span className="text-xs font-mono font-bold text-cyan-300">
                Generated {serverType === 'htaccess' ? '.htaccess Apache' : 'Nginx'} Rule
              </span>
              <button
                type="button"
                onClick={() => handleCopy(generateRedirectRule())}
                className="px-3 py-1 rounded-xl bg-cyan-500/10 hover:bg-cyan-500/20 text-cyan-300 border border-cyan-500/30 text-xs font-mono font-bold flex items-center gap-1.5 cursor-pointer"
              >
                <Copy className="w-3 h-3" />
                <span>{copied ? 'Copied Rule!' : 'Copy Rule'}</span>
              </button>
            </div>
            <textarea
              rows={5}
              readOnly
              value={generateRedirectRule()}
              className="w-full p-3 rounded-xl bg-slate-900 border border-slate-800 text-xs font-mono text-cyan-200 focus:outline-none"
            />
          </div>
        </div>
      )}

      {/* 5. Disavow File Generator View */}
      {mode === 'disavow' && (
        <div className="space-y-5">
          <div className="p-4 rounded-2xl bg-slate-950/90 border border-cyan-500/20 space-y-3">
            <label className="text-xs font-mono font-bold text-cyan-300">
              Disavow Domains & URLs (Google Search Console Format)
            </label>
            <textarea
              rows={6}
              value={disavowEntries}
              onChange={(e) => setDisavowEntries(e.target.value)}
              className="w-full p-2.5 rounded-xl bg-slate-900 border border-slate-700 text-xs font-mono text-cyan-100 focus:outline-none focus:border-cyan-400"
              placeholder="domain:spamsite.com&#10;https://spampage.org/toxic.html"
            />
            <p className="text-[11px] font-mono text-slate-400">
              Use <code className="text-cyan-300">domain:example.com</code> to disavow all links from an entire domain, or enter full URLs for single page disavowal.
            </p>
          </div>

          <div className="p-4 rounded-2xl bg-slate-950 border border-cyan-500/30 space-y-3">
            <div className="flex items-center justify-between">
              <span className="text-xs font-mono font-bold text-cyan-300">Google Disavow .txt Preview</span>
              <div className="flex gap-2">
                <button
                  type="button"
                  onClick={() => handleCopy(disavowEntries)}
                  className="px-2.5 py-1 rounded bg-slate-800 text-xs font-mono text-cyan-300 flex items-center gap-1 cursor-pointer"
                >
                  <Copy className="w-3 h-3" />
                  <span>Copy</span>
                </button>
                <button
                  type="button"
                  onClick={() => handleDownloadFile('disavow-links.txt', disavowEntries)}
                  className="px-2.5 py-1 rounded bg-cyan-500 text-slate-950 text-xs font-mono font-bold flex items-center gap-1 cursor-pointer"
                >
                  <Download className="w-3 h-3" />
                  <span>Download GSC .txt</span>
                </button>
              </div>
            </div>
            <textarea
              rows={6}
              readOnly
              value={disavowEntries}
              className="w-full p-3 rounded-xl bg-slate-900 border border-slate-800 text-xs font-mono text-rose-300 focus:outline-none"
            />
          </div>
        </div>
      )}
    </div>
  );
}
