import React, { useState, useMemo } from 'react';
import { Sparkles, HelpCircle, Check, Copy, Download, Bot, Shield, Globe, Plus, Trash2 } from 'lucide-react';
import { ToolComponentProps } from './registry';

interface BotRule {
  botName: string;
  allowed: boolean;
  crawlDelay?: number;
}

export default function RobotsTxtGenerator({ tool, onBack }: ToolComponentProps) {
  const [sitemapUrl, setSitemapUrl] = useState<string>('https://quickcalc.online/sitemap.xml');
  const [defaultPolicy, setDefaultPolicy] = useState<'allow' | 'disallow'>('allow');
  const [crawlDelay, setCrawlDelay] = useState<number>(0);
  const [disallowedPaths, setDisallowedPaths] = useState<string[]>(['/admin/', '/api/', '/private/', '/tmp/']);
  const [allowedPaths, setAllowedPaths] = useState<string[]>(['/assets/', '/public/']);
  const [newDisallowPath, setNewDisallowPath] = useState<string>('');
  const [newAllowPath, setNewAllowPath] = useState<string>('');
  const [blockAiScrapers, setBlockAiScrapers] = useState<boolean>(false);
  const [copied, setCopied] = useState<boolean>(false);

  const robotsTxtContent = useMemo(() => {
    const lines: string[] = [];

    lines.push('# ==============================================================================');
    lines.push('# Robots.txt Generated by Quick Calculator');
    lines.push('# https://quickcalc.online');
    lines.push('# ==============================================================================');
    lines.push('');

    // Default User-agent: *
    lines.push('User-agent: *');
    if (defaultPolicy === 'disallow') {
      lines.push('Disallow: /');
    } else {
      if (disallowedPaths.length === 0) {
        lines.push('Disallow:');
      } else {
        disallowedPaths.forEach((path) => {
          if (path.trim()) lines.push(`Disallow: ${path.trim()}`);
        });
      }
      allowedPaths.forEach((path) => {
        if (path.trim()) lines.push(`Allow: ${path.trim()}`);
      });
    }

    if (crawlDelay > 0) {
      lines.push(`Crawl-delay: ${crawlDelay}`);
    }
    lines.push('');

    // Block AI bots if opted in
    if (blockAiScrapers) {
      lines.push('# Block AI Data Scrapers & LLM Training Crawlers');
      const aiBots = ['GPTBot', 'ChatGPT-User', 'CCBot', 'anthropic-ai', 'ClaudeBot', 'PerplexityBot', 'Bytespider'];
      aiBots.forEach((bot) => {
        lines.push(`User-agent: ${bot}`);
        lines.push('Disallow: /');
        lines.push('');
      });
    }

    // Googlebot specific
    lines.push('# Googlebot Image Optimization');
    lines.push('User-agent: Googlebot-Image');
    lines.push('Allow: /*.png$');
    lines.push('Allow: /*.jpg$');
    lines.push('Allow: /*.webp$');
    lines.push('');

    // Sitemap declaration
    if (sitemapUrl.trim()) {
      lines.push('# Sitemap Location');
      lines.push(`Sitemap: ${sitemapUrl.trim()}`);
    }

    return lines.join('\n');
  }, [sitemapUrl, defaultPolicy, crawlDelay, disallowedPaths, allowedPaths, blockAiScrapers]);

  const handleCopy = () => {
    navigator.clipboard.writeText(robotsTxtContent);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
    const blob = new Blob([robotsTxtContent], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'robots.txt';
    a.click();
    URL.revokeObjectURL(url);
  };

  const addDisallow = () => {
    if (newDisallowPath.trim() && !disallowedPaths.includes(newDisallowPath.trim())) {
      setDisallowedPaths([...disallowedPaths, newDisallowPath.trim()]);
      setNewDisallowPath('');
    }
  };

  const addAllow = () => {
    if (newAllowPath.trim() && !allowedPaths.includes(newAllowPath.trim())) {
      setAllowedPaths([...allowedPaths, newAllowPath.trim()]);
      setNewAllowPath('');
    }
  };

  return (
    <div className="space-y-6 text-slate-100 font-sans">
      <div className="border-b border-slate-700/60 pb-4">
        <h2 className="text-xl sm:text-2xl font-bold font-display text-white tracking-tight">
          Robots.txt Generator - Search Engine Bot Crawler Directives Builder
        </h2>
        <p className="text-xs sm:text-sm text-slate-400 mt-1">
          Create standards-compliant robots.txt files with crawl delay parameters, disallowed directories, AI bot blocking, and sitemap declarations.
        </p>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
        {/* Left Inputs */}
        <div className="lg:col-span-6 space-y-4">
          <div className="p-4 sm:p-5 rounded-xl bg-slate-900/70 border border-slate-700/80 space-y-4">
            <h3 className="text-sm font-bold text-white flex items-center gap-1.5">
              <Bot className="w-4 h-4 text-cyan-400" /> Crawler Permissions & Rules
            </h3>

            {/* Sitemap URL */}
            <div className="space-y-1">
              <label className="text-xs font-semibold text-slate-300">XML Sitemap Canonical URL</label>
              <input
                type="text"
                value={sitemapUrl}
                onChange={(e) => setSitemapUrl(e.target.value)}
                placeholder="https://example.com/sitemap.xml"
                className="w-full px-3 py-2 rounded-lg bg-slate-950 border border-slate-700 font-mono text-xs text-white focus:outline-none focus:border-cyan-500"
              />
            </div>

            {/* Default Policy */}
            <div className="grid grid-cols-2 gap-3 pt-1">
              <div className="space-y-1">
                <label className="text-xs font-semibold text-slate-300">Default Access Policy</label>
                <div className="grid grid-cols-2 gap-1 bg-slate-950 p-1 rounded-lg border border-slate-800 text-xs">
                  <button
                    type="button"
                    onClick={() => setDefaultPolicy('allow')}
                    className={`py-1 rounded font-bold transition ${defaultPolicy === 'allow' ? 'bg-cyan-500 text-slate-950' : 'text-slate-400 hover:text-white'}`}
                  >
                    Allow All
                  </button>
                  <button
                    type="button"
                    onClick={() => setDefaultPolicy('disallow')}
                    className={`py-1 rounded font-bold transition ${defaultPolicy === 'disallow' ? 'bg-cyan-500 text-slate-950' : 'text-slate-400 hover:text-white'}`}
                  >
                    Block All
                  </button>
                </div>
              </div>

              <div className="space-y-1">
                <label className="text-xs font-semibold text-slate-300">Crawl Delay (Seconds)</label>
                <input
                  type="number"
                  min={0}
                  max={60}
                  value={crawlDelay}
                  onChange={(e) => setCrawlDelay(Number(e.target.value))}
                  placeholder="0 (no delay)"
                  className="w-full px-3 py-1.5 rounded-lg bg-slate-950 border border-slate-700 font-mono text-xs text-white focus:outline-none focus:border-cyan-500"
                />
              </div>
            </div>

            {/* AI Scraper Block Toggle */}
            <div className="pt-2 border-t border-slate-800">
              <label className="flex items-center gap-2 text-xs text-slate-300 cursor-pointer">
                <input
                  type="checkbox"
                  checked={blockAiScrapers}
                  onChange={(e) => setBlockAiScrapers(e.target.checked)}
                  className="rounded bg-slate-950 border-slate-700 text-cyan-500 focus:ring-0"
                />
                <span className="font-semibold text-purple-300">Block AI Crawlers & Scrapers (GPTBot, ClaudeBot, Perplexity)</span>
              </label>
            </div>

            {/* Disallowed Paths */}
            <div className="space-y-2 pt-2 border-t border-slate-800">
              <label className="text-xs font-semibold text-slate-300 block">Disallowed Paths (Disallow: /path/)</label>
              <div className="flex gap-2">
                <input
                  type="text"
                  value={newDisallowPath}
                  onChange={(e) => setNewDisallowPath(e.target.value)}
                  placeholder="/admin/ or /cgi-bin/"
                  className="flex-1 px-3 py-1.5 rounded-lg bg-slate-950 border border-slate-700 font-mono text-xs text-white focus:outline-none focus:border-cyan-500"
                />
                <button
                  type="button"
                  onClick={addDisallow}
                  className="px-3 py-1.5 rounded-lg bg-slate-800 hover:bg-slate-700 text-cyan-400 text-xs font-bold flex items-center gap-1 transition"
                >
                  <Plus className="w-3.5 h-3.5" /> Add
                </button>
              </div>

              <div className="flex flex-wrap gap-1.5 pt-1">
                {disallowedPaths.map((p) => (
                  <span
                    key={p}
                    className="px-2 py-0.5 rounded bg-rose-500/10 border border-rose-500/20 text-rose-300 font-mono text-[11px] flex items-center gap-1.5"
                  >
                    {p}
                    <button
                      type="button"
                      onClick={() => setDisallowedPaths(disallowedPaths.filter((item) => item !== p))}
                      className="hover:text-rose-100"
                    >
                      ×
                    </button>
                  </span>
                ))}
              </div>
            </div>
          </div>
        </div>

        {/* Right Output View */}
        <div className="lg:col-span-6 flex flex-col space-y-3">
          <div className="p-4 sm:p-5 rounded-xl bg-slate-900/70 border border-slate-700/80 flex-1 flex flex-col justify-between space-y-3">
            <div className="flex items-center justify-between text-xs">
              <span className="font-semibold text-slate-200">Generated robots.txt Preview</span>
              <div className="flex items-center gap-2">
                <button
                  type="button"
                  onClick={handleCopy}
                  className="px-2.5 py-1 rounded-lg bg-slate-800 hover:bg-slate-700 text-cyan-400 font-medium flex items-center gap-1 transition"
                >
                  {copied ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
                  {copied ? 'Copied' : 'Copy'}
                </button>
                <button
                  type="button"
                  onClick={handleDownload}
                  className="px-3 py-1 rounded-lg bg-cyan-500 hover:bg-cyan-400 text-slate-950 font-bold flex items-center gap-1 transition"
                >
                  <Download className="w-3.5 h-3.5" /> Download
                </button>
              </div>
            </div>

            <textarea
              readOnly
              rows={14}
              value={robotsTxtContent}
              className="w-full flex-1 px-3 py-2.5 rounded-lg bg-slate-950 border border-slate-800 font-mono text-xs text-cyan-300 focus:outline-none resize-none leading-relaxed select-all"
            />

            <p className="text-[11px] text-slate-500">
              Upload this file directly to your website root directory at <code className="text-slate-400">/robots.txt</code>.
            </p>
          </div>
        </div>
      </div>

      {/* 3-Line FAQ */}
      <div className="p-4 sm:p-5 rounded-xl bg-slate-900/70 border border-slate-700/80 space-y-3">
        <h4 className="text-xs sm:text-sm font-bold text-slate-200 flex items-center gap-1.5">
          <HelpCircle className="w-4 h-4 text-cyan-400" /> Frequently Asked Questions
        </h4>
        <div className="space-y-2 text-xs text-slate-400 divide-y divide-slate-800/80">
          <div className="pt-2">
            <strong className="text-slate-300">Where should the robots.txt file be uploaded on my domain?</strong>
            <p className="mt-0.5">The robots.txt file must reside in the top-level root directory (e.g. `https://example.com/robots.txt`) to be parsed by web crawlers.</p>
          </div>
          <div className="pt-2">
            <strong className="text-slate-300">Does Disallow in robots.txt prevent pages from being indexed?</strong>
            <p className="mt-0.5">No, Disallow prevents crawling but Google can still index URLs if external links reference them; use &lt;meta name="robots" content="noindex"&gt; for complete de-indexing.</p>
          </div>
          <div className="pt-2">
            <strong className="text-slate-300">How do I verify if my robots.txt is valid?</strong>
            <p className="mt-0.5">Use Google Search Console's Robots Testing Tool to verify that crawler bots can fetch public URLs without unintended restrictions.</p>
          </div>
        </div>
      </div>
    </div>
  );
}
